### ISSUE TITLE
Losing last word if not followed by punctuation?

### ISSUE THREAD

**Issue by IvyJL** [Hedera-Lang-Learn/hedera#112]
When a text is entered for lemmatization, the final word is lost apparently if not followed by a period.

**Comment by bilbe** [comment]
Yes, I think this is the case. I tried this on my local machine and the "original_text" has the last word, but the "data" doesn't.

I think this must be happening in /lemmatization/services/base.py in tokenization. I think the "pairwise" function is expecting pairs(!) and since this is no space or punctuation or whatever, it is unhappy.
