### ISSUE TITLE
Duplicate entries for "honoris"

### ISSUE THREAD

**Issue by bilbe** [Hedera-Lang-Learn/hedera#217]
This is probably a lattice loading issue, and maybe we can just delete one entry in the admin interface, but maybe not.

![image](https://user-images.githubusercontent.com/5712116/88100998-5e2a6f80-cb6b-11ea-8198-96c8268e23f2.png)

**Comment by IvyJL** [comment]
I might be misunderstanding the problem, but I think this is the desired behavior at least for now. The issue is that the "same" word can have its nom. sg. as _honor_ or _honos_. A student might learn it one way or the other (although I think most intro books have _honor_)

It's essentially a doublet like "gray" and "grey" in English.

 I've got both _honor_ and _honos_ in the spreadsheet since they're both classical: you can find them both in Lewis & Short's lexicon and Morpheus recognizes both.

It's not quite the same situation as _nuntius_ and _nuncius_, since nuncius seems a purely medieval Latin thing: it doesn't appear in Lewis & Short and Morpheus doesn't recognize it.

In terms of disambiguating, often it won't matter if you choose _honor_ or _honos_ since most of their forms are identical. But for if the text has _honos_, you probably want to pick _honos_, since a student who learned _honor_ may well not know that _honos_ means the same thing. They can certainly mark it as learned immediately, if they want.

**Comment by bilbe** [comment]
Capisco! I didn't actually notice the difference between the -r and the -s, since the definition was the same. Obviously reading just a bit too fast.
